### ISSUE TITLE
Errata for https://www.arroyo.dev/blog

### ISSUE THREAD

**Issue by breezykermo** [ArroyoSystems/arroyo-docs#69]
I have found a couple of typos, for example in https://www.arroyo.dev/blog/using-kafka-with-rust:

> Partition: A single log for a topic; messages within each partition are _orerded_

**Comment by breezykermo** [comment]
Another in https://www.arroyo.dev/blog/udf-parsing-tutorial: 
> then counting _theÆ_ number of records in each group

**Comment by mwylde** [comment]
Thanks for the corrections! The blog source isn't public but I'll get those fixes in.

**Comment by breezykermo** [comment]
Great, thanks! Are issues like this are the best place to report other errata for the blog and similar in the future?
